// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4k6Kg1ZBfWbkM30wVxC16byqcooDhvQE',
    appId: '1:944298492813:web:ec1deab35aedf1ed2f33c4',
    messagingSenderId: '944298492813',
    projectId: 'articulation-supports',
    authDomain: 'articulation-supports.firebaseapp.com',
    storageBucket: 'articulation-supports.appspot.com',
    measurementId: 'G-79DQ3L4MCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Ao0ckYcxdbN98j3XxfLLMvkDvC1NaTU',
    appId: '1:944298492813:android:21b07c884387a4dc2f33c4',
    messagingSenderId: '944298492813',
    projectId: 'articulation-supports',
    storageBucket: 'articulation-supports.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiOonW0dIb7VHC8ABE6kqqtHoxa9X300',
    appId: '1:944298492813:ios:3f419d7aa921016d2f33c4',
    messagingSenderId: '944298492813',
    projectId: 'articulation-supports',
    storageBucket: 'articulation-supports.appspot.com',
    iosClientId: '944298492813-vcpc2j5hrfn3s5rhhdpe1ds4kr12voqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.articulationSupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiOonW0dIb7VHC8ABE6kqqtHoxa9X300',
    appId: '1:944298492813:ios:3f419d7aa921016d2f33c4',
    messagingSenderId: '944298492813',
    projectId: 'articulation-supports',
    storageBucket: 'articulation-supports.appspot.com',
    iosClientId: '944298492813-vcpc2j5hrfn3s5rhhdpe1ds4kr12voqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.articulationSupport',
  );
}
