// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import './config/config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Configs.webConfigs['apiKey']!,
    appId: Configs.webConfigs['appId']!,
    messagingSenderId: Configs.webConfigs['messagingSenderId']!,
    projectId: Configs.webConfigs['projectId']!,
    authDomain: Configs.webConfigs['authDomain']!,
    storageBucket: Configs.webConfigs['storageBucket']!,
    measurementId: Configs.webConfigs['measurementId']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Configs.androidConfigs['apiKey']!,
    appId: Configs.androidConfigs['appId']!,
    messagingSenderId: Configs.androidConfigs['messagingSenderId']!,
    projectId: Configs.androidConfigs['projectId']!,
    storageBucket: Configs.androidConfigs['storageBucket']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Configs.iosConfigs['apiKey']!,
    appId: Configs.iosConfigs['appId']!,
    messagingSenderId: Configs.iosConfigs['messagingSenderId']!,
    projectId: Configs.iosConfigs['projectId']!,
    storageBucket: Configs.iosConfigs['storageBucket']!,
    iosClientId: Configs.iosConfigs['iosClientId']!,
    iosBundleId: Configs.iosConfigs['iosBundleId']!,
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: Configs.macConfigs['apiKey']!,
    appId: Configs.macConfigs['appId']!,
    messagingSenderId: Configs.macConfigs['messagingSenderId']!,
    projectId: Configs.macConfigs['projectId']!,
    storageBucket: Configs.macConfigs['storageBucket']!,
    iosClientId: Configs.macConfigs['iosClientId']!,
    iosBundleId: Configs.macConfigs['iosBundleId']!,
  );
}
